name: Quality assurance

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        php: [ '8.1','8.2','8.3','8.4' ]
    runs-on: ubuntu-24.04
    steps:

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phing:v3

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: phing composer:install

      - name: QA
        run: PHP_CS_FIXER_IGNORE_ENV=yes phing composer:validate composer:audit php:lint cs:check
